import type { SettingDefinition } from './definition.js';

const hotCornerActionChoices = [
  { value: 0, label: 'No action' },
  { value: 1, label: 'No action' },
  { value: 2, label: 'Mission Control' },
  { value: 3, label: 'Application windows' },
  { value: 4, label: 'Desktop' },
  { value: 5, label: 'Start screen saver' },
  { value: 6, label: 'Disable screen saver' },
  { value: 10, label: 'Put display to sleep' },
  { value: 11, label: 'Launchpad' },
  { value: 12, label: 'Notification Center' },
  { value: 13, label: 'Lock screen' },
  { value: 14, label: 'Quick Note' },
];

const hotCornerModifierChoices = [
  { value: 0, label: 'None' },
  { value: 131072, label: 'Shift' },
  { value: 262144, label: 'Control' },
  { value: 524288, label: 'Option' },
  { value: 1048576, label: 'Command' },
];

function hotCorner(position: string, label: string): SettingDefinition[] {
  return [
    {
      section: 'hot-corners',
      key: `${label}-action`,
      description: 'Hot corner action.',
      choices: hotCornerActionChoices,
      domain: 'com.apple.dock',
      defaultsKey: `wvous-${position}-corner`,
      type: 'integer',
      restart: 'Dock',
    },
    {
      section: 'hot-corners',
      key: `${label}-modifier`,
      description: 'Modifier keys that must be held for the corner to trigger.',
      choices: hotCornerModifierChoices,
      domain: 'com.apple.dock',
      defaultsKey: `wvous-${position}-modifier`,
      type: 'integer',
      restart: 'Dock',
    },
  ];
}

/** Dock appearance and behavior, Mission Control, and hot corners. */
export const dockSettings: SettingDefinition[] = [
  {
    section: 'dock',
    key: 'auto-hide',
    description: 'Automatically hide the Dock until the pointer reaches the screen edge.',
    domain: 'com.apple.dock',
    defaultsKey: 'autohide',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'auto-hide-delay',
    description:
      'Seconds the pointer must rest at the screen edge before the hidden Dock appears. 0 shows it instantly.',
    domain: 'com.apple.dock',
    defaultsKey: 'autohide-delay',
    type: 'float',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'auto-hide-animation-duration',
    description: 'Seconds the Dock show/hide animation takes; lower feels snappier.',
    domain: 'com.apple.dock',
    defaultsKey: 'autohide-time-modifier',
    type: 'float',
    macosDefault: 0.5,
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'icon-size',
    description: 'Dock icon size.',
    domain: 'com.apple.dock',
    defaultsKey: 'tilesize',
    type: 'integer',
    range: { min: 16, max: 128, unit: 'px' },
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'magnification',
    description: 'Magnify Dock icons under the pointer.',
    domain: 'com.apple.dock',
    defaultsKey: 'magnification',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'magnified-icon-size',
    description: 'Icon size at the center of magnification.',
    domain: 'com.apple.dock',
    defaultsKey: 'largesize',
    type: 'integer',
    range: { min: 16, max: 128, unit: 'px' },
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'position',
    description: 'Which screen edge the Dock lives on.',
    domain: 'com.apple.dock',
    defaultsKey: 'orientation',
    type: 'string',
    choices: [
      { value: 'left', label: 'Left' },
      { value: 'bottom', label: 'Bottom' },
      { value: 'right', label: 'Right' },
    ],
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'minimize-effect',
    description: 'Window-minimize animation.',
    domain: 'com.apple.dock',
    defaultsKey: 'mineffect',
    type: 'string',
    choices: [
      { value: 'genie', label: 'Genie' },
      { value: 'scale', label: 'Scale' },
      { value: 'suck', label: 'Suck (hidden option)' },
    ],
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'minimize-into-app-icon',
    description: "Minimize windows into their app's Dock icon instead of a separate Dock tile.",
    domain: 'com.apple.dock',
    defaultsKey: 'minimize-to-application',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'show-recents',
    description: 'Show a section of recently used apps at the end of the Dock.',
    domain: 'com.apple.dock',
    defaultsKey: 'show-recents',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'show-indicator-lights',
    description: 'Show the small dot under running applications.',
    domain: 'com.apple.dock',
    defaultsKey: 'show-process-indicators',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'dim-hidden-apps',
    description: 'Dim the Dock icons of hidden applications (a hidden preference).',
    domain: 'com.apple.dock',
    defaultsKey: 'showhidden',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'launch-animation',
    description: 'Bounce Dock icons while their application launches.',
    domain: 'com.apple.dock',
    defaultsKey: 'launchanim',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'scroll-to-open',
    description: "Scroll up on a Dock icon to show the app's windows (a hidden preference).",
    domain: 'com.apple.dock',
    defaultsKey: 'scroll-to-open',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'spring-load-all-items',
    description: 'Enable spring-loading (hover-to-open) for every Dock item.',
    domain: 'com.apple.dock',
    defaultsKey: 'enable-spring-load-actions-on-all-items',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'dock',
    key: 'pinned-applications',
    description:
      'The apps pinned to the Dock, as an ordered JSON array of app URLs derived from the Dock tiles. Spacers and folders are not captured; applying rebuilds the pinned apps from this list.',
    domain: 'com.apple.dock',
    defaultsKey: 'persistent-apps',
    type: 'plist',
    special: 'dock-applications',
    keywords: ['dock apps'],
    restart: 'Dock',
  },
  {
    section: 'mission-control',
    key: 'rearrange-spaces-by-use',
    description: 'Automatically rearrange Spaces based on most recent use.',
    domain: 'com.apple.dock',
    defaultsKey: 'mru-spaces',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'mission-control',
    key: 'group-windows-by-app',
    description: 'Group windows by application in Mission Control.',
    domain: 'com.apple.dock',
    defaultsKey: 'expose-group-apps',
    type: 'boolean',
    restart: 'Dock',
  },
  {
    section: 'mission-control',
    key: 'displays-have-separate-spaces',
    description: 'Give each display its own set of Spaces.',
    domain: 'com.apple.spaces',
    defaultsKey: 'spans-displays',
    type: 'boolean',
    requiresLogout: true,
  },
  {
    section: 'mission-control',
    key: 'switch-space-on-activate',
    description: 'When switching to an app, jump to a Space with its open windows.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleSpacesSwitchOnActivate',
    type: 'boolean',
  },
  ...hotCorner('tl', 'top-left'),
  ...hotCorner('tr', 'top-right'),
  ...hotCorner('bl', 'bottom-left'),
  ...hotCorner('br', 'bottom-right'),
];
