import type { SettingDefinition } from './definition.js';

/** Finder behavior, desktop icons, and .DS_Store hygiene. */
export const finderSettings: SettingDefinition[] = [
  {
    section: 'finder',
    key: 'show-hidden-files',
    description: 'Show dotfiles and other hidden files in Finder windows.',
    domain: 'com.apple.finder',
    defaultsKey: 'AppleShowAllFiles',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'show-all-extensions',
    description: 'Show every filename extension, even for known file types.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleShowAllExtensions',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'show-path-bar',
    description: 'Show the path bar at the bottom of Finder windows.',
    domain: 'com.apple.finder',
    defaultsKey: 'ShowPathbar',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'show-status-bar',
    description: 'Show the status bar (item count, free space) in Finder windows.',
    domain: 'com.apple.finder',
    defaultsKey: 'ShowStatusBar',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'posix-path-in-title',
    label: 'POSIX Path in Window Title',
    description: 'Show the full POSIX path in the Finder window title (a hidden preference).',
    domain: 'com.apple.finder',
    defaultsKey: '_FXShowPosixPathInTitle',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'sort-folders-first',
    description: 'Keep folders on top when sorting by name.',
    domain: 'com.apple.finder',
    defaultsKey: '_FXSortFoldersFirst',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'default-view-style',
    description: 'Default Finder view.',
    domain: 'com.apple.finder',
    defaultsKey: 'FXPreferredViewStyle',
    type: 'string',
    choices: [
      { value: 'Nlsv', label: 'List' },
      { value: 'icnv', label: 'Icons' },
      { value: 'clmv', label: 'Columns' },
      { value: 'glyv', label: 'Gallery' },
    ],
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'default-search-scope',
    description: 'Where Finder search starts.',
    domain: 'com.apple.finder',
    defaultsKey: 'FXDefaultSearchScope',
    type: 'string',
    choices: [
      { value: 'SCcf', label: 'Current folder' },
      { value: 'SCev', label: 'This Mac' },
      { value: 'SCsp', label: 'Previous scope' },
    ],
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'new-window-target',
    description: 'What new Finder windows open to.',
    domain: 'com.apple.finder',
    defaultsKey: 'NewWindowTarget',
    type: 'string',
    choices: [
      { value: 'PfHm', label: 'Home folder' },
      { value: 'PfDe', label: 'Desktop' },
      { value: 'PfDo', label: 'Documents' },
      { value: 'PfAF', label: 'Recents' },
      { value: 'PfVo', label: 'Computer' },
      { value: 'PfLo', label: 'Custom location' },
    ],
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'extension-change-warning',
    description: 'Warn before changing a filename extension.',
    domain: 'com.apple.finder',
    defaultsKey: 'FXEnableExtensionChangeWarning',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'empty-trash-after-30-days',
    description: 'Automatically remove items from the Trash after 30 days.',
    domain: 'com.apple.finder',
    defaultsKey: 'FXRemoveOldTrashItems',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'quit-menu-item',
    description:
      'Add a Quit menu item to Finder (⌘Q closes all Finder windows; a hidden preference).',
    domain: 'com.apple.finder',
    defaultsKey: 'QuitMenuItem',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'desktop-show-internal-drives',
    description: 'Show internal hard drives on the desktop.',
    domain: 'com.apple.finder',
    defaultsKey: 'ShowHardDrivesOnDesktop',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'desktop-show-external-drives',
    description: 'Show external drives on the desktop.',
    domain: 'com.apple.finder',
    defaultsKey: 'ShowExternalHardDrivesOnDesktop',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'desktop-show-removable-media',
    description: 'Show CDs, DVDs, and other removable media on the desktop.',
    domain: 'com.apple.finder',
    defaultsKey: 'ShowRemovableMediaOnDesktop',
    type: 'boolean',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'standard-view-settings',
    description:
      'Default view options (icon size, arrangement, text size) for icon, list, column, and gallery views. Structured value.',
    domain: 'com.apple.finder',
    defaultsKey: 'StandardViewSettings',
    type: 'plist',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'search-view-settings',
    description: 'View options used for search results and smart folders. Structured value.',
    domain: 'com.apple.finder',
    defaultsKey: 'FK_StandardViewSettings',
    type: 'plist',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'desktop-view-settings',
    description:
      'Desktop icon layout: icon size, grid spacing, text size, label position. Structured value.',
    domain: 'com.apple.finder',
    defaultsKey: 'DesktopViewSettings',
    type: 'plist',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'info-panes-expanded',
    description: 'Which sections of the Get Info panel are expanded. Structured value.',
    domain: 'com.apple.finder',
    defaultsKey: 'FXInfoPanesExpanded',
    type: 'plist',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'toolbar-configuration',
    description: 'Finder window toolbar layout and display mode. Structured value.',
    domain: 'com.apple.finder',
    defaultsKey: 'NSToolbar Configuration Browser',
    type: 'plist',
    restart: 'Finder',
  },
  {
    section: 'finder',
    key: 'spring-loading-enabled',
    description: 'Spring-loading: hovering a dragged item over a folder opens it.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.springing.enabled',
    type: 'boolean',
  },
  {
    section: 'finder',
    key: 'spring-loading-delay',
    description: 'Seconds a dragged item must hover before spring-loading opens the folder.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.springing.delay',
    type: 'float',
    macosDefault: 0.5,
  },
  {
    section: 'finder',
    key: 'avoid-ds-store-on-network',
    label: 'Avoid .DS_Store on Network Volumes',
    description: 'Do not write .DS_Store files on network volumes.',
    domain: 'com.apple.desktopservices',
    defaultsKey: 'DSDontWriteNetworkStores',
    type: 'boolean',
  },
  {
    section: 'finder',
    key: 'avoid-ds-store-on-usb',
    label: 'Avoid .DS_Store on USB Volumes',
    description: 'Do not write .DS_Store files on USB volumes.',
    domain: 'com.apple.desktopservices',
    defaultsKey: 'DSDontWriteUSBStores',
    type: 'boolean',
  },
];
