import type { SettingDefinition } from './definition.js';

const bluetoothTrackpadDomain = 'com.apple.driver.AppleBluetoothMultitouch.trackpad';

/** Trackpad and mouse behavior. */
export const inputSettings: SettingDefinition[] = [
  {
    section: 'trackpad',
    key: 'tap-to-click',
    description: 'Register a light tap on the trackpad as a click.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'Clicking',
    type: 'boolean',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'secondary-click',
    description: 'Register a two-finger tap or click as a secondary (right) click.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadRightClick',
    type: 'boolean',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'three-finger-drag',
    description: 'Drag windows and select text by moving three fingers on the trackpad.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadThreeFingerDrag',
    type: 'boolean',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'tracking-speed',
    description: 'Trackpad pointer tracking speed.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.trackpad.scaling',
    type: 'float',
    keywords: ['speed', 'pointer'],
    range: { min: 0, max: 3 },
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'force-click',
    description: 'Enable Force Click and haptic feedback for look-up and data detectors.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.trackpad.forceClick',
    type: 'boolean',
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'natural-scrolling',
    description:
      'Scroll content in the direction your fingers move (true) or the classic direction (false).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.swipescrolldirection',
    type: 'boolean',
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'click-firmness',
    description: 'Force needed for a click.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'FirstClickThreshold',
    type: 'integer',
    choices: [
      { value: 0, label: 'Light' },
      { value: 1, label: 'Medium' },
      { value: 2, label: 'Firm' },
    ],
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'force-click-firmness',
    description: 'Force needed for a Force Click.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'SecondClickThreshold',
    type: 'integer',
    choices: [
      { value: 0, label: 'Light' },
      { value: 1, label: 'Medium' },
      { value: 2, label: 'Firm' },
    ],
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'click-feedback',
    description: 'Haptic click feedback.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'ActuateDetents',
    type: 'integer',
    choices: [
      { value: 0, label: 'Silent clicking' },
      { value: 1, label: 'Normal clicking' },
    ],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'three-finger-tap-gesture',
    description: 'Three-finger tap gesture.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadThreeFingerTapGesture',
    type: 'integer',
    choices: [
      { value: 0, label: 'Off' },
      { value: 2, label: 'Look Up & data detectors' },
    ],
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'two-finger-double-tap-gesture',
    description: 'Two-finger double-tap (smart zoom).',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadTwoFingerDoubleTapGesture',
    type: 'integer',
    choices: [
      { value: 0, label: 'Off' },
      { value: 1, label: 'Smart zoom' },
    ],
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'right-edge-swipe-gesture',
    description:
      'Two-finger swipe from the right edge (Notification Center): 0 = off; the stored code selects the configured action.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadTwoFingerFromRightEdgeSwipeGesture',
    type: 'integer',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'four-finger-vertical-swipe-gesture',
    description:
      'Four-finger vertical swipe (Mission Control / App Exposé): 0 = off; the stored code selects the configured action.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadFourFingerVertSwipeGesture',
    type: 'integer',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'four-finger-horizontal-swipe-gesture',
    description:
      'Four-finger horizontal swipe (switch full-screen apps and Spaces): 0 = off; the stored code selects the configured action.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadFourFingerHorizSwipeGesture',
    type: 'integer',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'four-finger-pinch-gesture',
    description:
      'Four-finger pinch (Launchpad / show desktop): 0 = off; the stored code selects the configured action.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadFourFingerPinchGesture',
    type: 'integer',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'trackpad',
    key: 'five-finger-pinch-gesture',
    description: 'Five-finger pinch: 0 = off; the stored code selects the configured action.',
    domain: 'com.apple.AppleMultitouchTrackpad',
    defaultsKey: 'TrackpadFiveFingerPinchGesture',
    type: 'integer',
    mirrorDomains: [bluetoothTrackpadDomain],
    requiresLogout: true,
  },
  {
    section: 'mouse',
    key: 'tracking-speed',
    description: 'Mouse pointer tracking speed.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.mouse.scaling',
    type: 'float',
    keywords: ['speed', 'pointer'],
    range: { min: 0, max: 3 },
    requiresLogout: true,
  },
];
