import type { SettingDefinition } from './definition.js';

/** Appearance, menu bar clock, and window management. */
export const interfaceSettings: SettingDefinition[] = [
  {
    section: 'appearance',
    key: 'switch-appearance-automatically',
    description: 'Switch between light and dark appearance automatically with the time of day.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleInterfaceStyleSwitchesAutomatically',
    type: 'boolean',
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'interface-style',
    description:
      'Fixed appearance when not switching automatically; unset means light. Takes effect after logging out and back in.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleInterfaceStyle',
    type: 'string',
    choices: [{ value: 'Dark', label: 'Dark' }],
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'accent-color',
    description: 'Accent color. Unset means multicolor.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleAccentColor',
    type: 'integer',
    keywords: ['theme', 'color'],
    choices: [
      { value: -1, label: 'Graphite' },
      { value: 0, label: 'Red' },
      { value: 1, label: 'Orange' },
      { value: 2, label: 'Yellow' },
      { value: 3, label: 'Green' },
      { value: 4, label: 'Blue' },
      { value: 5, label: 'Purple' },
      { value: 6, label: 'Pink' },
    ],
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'aqua-color-variant',
    description:
      'Legacy blue/graphite appearance switch that macOS keeps in sync with the accent color.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleAquaColorVariant',
    type: 'integer',
    choices: [
      { value: 1, label: 'Blue' },
      { value: 6, label: 'Graphite' },
    ],
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'icon-tint-color',
    description: 'Icon and widget tint color by name (e.g. "Graphite"), introduced in macOS 26.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleIconAppearanceTintColor',
    type: 'string',
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'highlight-color',
    description: 'Text selection highlight color as RGB components plus a name.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleHighlightColor',
    type: 'string',
    requiresLogout: true,
  },
  {
    section: 'appearance',
    key: 'show-scroll-bars',
    description: 'When scroll bars appear.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleShowScrollBars',
    type: 'string',
    choices: [
      { value: 'Automatic', label: 'Based on input device' },
      { value: 'WhenScrolling', label: 'When scrolling' },
      { value: 'Always', label: 'Always' },
    ],
  },
  {
    section: 'appearance',
    key: 'click-scroll-bar-to-jump',
    description: 'Clicking a scroll bar jumps to the clicked spot (true) or the next page (false).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleScrollerPagingBehavior',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'clock-show-am-pm',
    description: 'Show AM/PM in the menu bar clock.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'ShowAMPM',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'clock-show-date',
    description: 'Menu bar clock date display.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'ShowDate',
    type: 'integer',
    choices: [
      { value: 0, label: 'When space allows' },
      { value: 1, label: 'Always' },
      { value: 2, label: 'Never' },
    ],
  },
  {
    section: 'menu-bar',
    key: 'clock-show-day-of-week',
    description: 'Show the day of the week in the menu bar clock.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'ShowDayOfWeek',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'clock-show-seconds',
    description: 'Show seconds in the menu bar clock.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'ShowSeconds',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'auto-hide-menu-bar',
    description: 'Automatically hide and show the menu bar.',
    domain: 'NSGlobalDomain',
    defaultsKey: '_HIHideMenuBar',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'menu-bar-in-fullscreen',
    description: 'Show the menu bar in full screen (hover is still required when hidden).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleMenuBarVisibleInFullscreen',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'clock-analog',
    description: 'Show the menu bar clock as a tiny analog face instead of digits.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'IsAnalog',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'clock-flash-separators',
    description: 'Flash the time separators every second.',
    domain: 'com.apple.menuextra.clock',
    defaultsKey: 'FlashDateSeparators',
    type: 'boolean',
  },
  {
    section: 'menu-bar',
    key: 'battery-show-percentage',
    description: 'Show the battery percentage in the menu bar.',
    domain: 'com.apple.controlcenter',
    defaultsKey: 'BatteryShowPercentage',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'stage-manager',
    description: 'Enable Stage Manager window organization.',
    domain: 'com.apple.WindowManager',
    defaultsKey: 'GloballyEnabled',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'tiled-window-margins',
    description: 'Leave a small margin between windows tiled to the screen edges.',
    domain: 'com.apple.WindowManager',
    defaultsKey: 'EnableTiledWindowMargins',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'hide-desktop-icons',
    description:
      'Hide desktop icons unless the desktop is clicked (macOS "Desktop & Stage Manager" behavior).',
    domain: 'com.apple.WindowManager',
    defaultsKey: 'StandardHideDesktopIcons',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'click-wallpaper-to-reveal-desktop',
    description: 'Clicking the wallpaper hides all windows to reveal the desktop.',
    domain: 'com.apple.WindowManager',
    defaultsKey: 'EnableStandardClickToShowDesktop',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'hide-widgets',
    description: 'Hide desktop widgets outside of Stage Manager.',
    domain: 'com.apple.WindowManager',
    defaultsKey: 'StandardHideWidgets',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'window-animations',
    description:
      'Animate opening windows (a hidden preference; false makes windows appear instantly).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticWindowAnimationsEnabled',
    type: 'boolean',
  },
  {
    section: 'windows',
    key: 'window-resize-time',
    description: 'Duration in seconds of window resize animations (a hidden preference).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSWindowResizeTime',
    type: 'float',
    macosDefault: 0.2,
  },
  {
    section: 'windows',
    key: 'double-click-title-bar',
    description: 'What double-clicking a window title bar does.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleActionOnDoubleClick',
    type: 'string',
    choices: [
      { value: 'Maximize', label: 'Zoom' },
      { value: 'Minimize', label: 'Minimize' },
      { value: 'Fill', label: 'Fill screen' },
      { value: 'None', label: 'Do nothing' },
    ],
  },
  {
    section: 'windows',
    key: 'prefer-tabs',
    description: 'When to prefer tabs over new windows.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleWindowTabbingMode',
    type: 'string',
    choices: [
      { value: 'always', label: 'Always' },
      { value: 'fullscreen', label: 'In full screen only' },
      { value: 'manual', label: 'Never' },
    ],
  },
];
