import type { SettingDefinition } from './definition.js';

/** Keyboard behavior and system-wide text substitution. */
export const keyboardSettings: SettingDefinition[] = [
  {
    section: 'keyboard',
    key: 'key-repeat-rate',
    description:
      'How fast a held key repeats. Lower is faster; 1 is faster than System Settings allows (its fastest is 2).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'KeyRepeat',
    type: 'integer',
    keywords: ['typing', 'keyboard speed'],
    range: { min: 1, max: 120 },
    requiresLogout: true,
  },
  {
    section: 'keyboard',
    key: 'initial-key-repeat-delay',
    description:
      'How long a key must be held before it starts repeating. Lower is shorter; 15 is the shortest System Settings allows.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'InitialKeyRepeat',
    type: 'integer',
    range: { min: 15, max: 120 },
    requiresLogout: true,
  },
  {
    section: 'keyboard',
    key: 'press-and-hold-shows-accents',
    description:
      'When true, holding a key shows the accent-character popup instead of repeating the key.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'ApplePressAndHoldEnabled',
    type: 'boolean',
    requiresLogout: true,
  },
  {
    section: 'keyboard',
    key: 'full-keyboard-access',
    description: 'Keyboard navigation of controls (Tab moves focus everywhere when set to all).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleKeyboardUIMode',
    type: 'integer',
    choices: [
      { value: 0, label: 'Text boxes and lists only' },
      { value: 1, label: 'Text boxes and lists only' },
      { value: 2, label: 'All controls' },
      { value: 3, label: 'All controls' },
    ],
  },
  {
    section: 'keyboard',
    key: 'fn-key-behavior',
    description: 'What pressing the Fn/Globe key does.',
    domain: 'com.apple.HIToolbox',
    defaultsKey: 'AppleFnUsageType',
    type: 'integer',
    choices: [
      { value: 0, label: 'Do nothing' },
      { value: 1, label: 'Change input source' },
      { value: 2, label: 'Show emoji and symbols' },
      { value: 3, label: 'Start dictation' },
    ],
  },
  {
    section: 'text',
    key: 'auto-capitalization',
    description: 'Automatically capitalize the first word of sentences as you type.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticCapitalizationEnabled',
    type: 'boolean',
  },
  {
    section: 'text',
    key: 'auto-period-substitution',
    description: 'Insert a period when you double-tap the space bar.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticPeriodSubstitutionEnabled',
    type: 'boolean',
  },
  {
    section: 'text',
    key: 'smart-quotes',
    description: 'Replace straight quotes with curly typographic quotes as you type.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticQuoteSubstitutionEnabled',
    type: 'boolean',
  },
  {
    section: 'text',
    key: 'smart-dashes',
    description: 'Replace double hyphens with em dashes as you type.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticDashSubstitutionEnabled',
    type: 'boolean',
  },
  {
    section: 'text',
    key: 'auto-spelling-correction',
    description: 'Correct spelling automatically as you type.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticSpellingCorrectionEnabled',
    type: 'boolean',
  },
  {
    section: 'text',
    key: 'inline-predictive-text',
    description: 'Show inline predictive text completions as you type.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSAutomaticInlinePredictionEnabled',
    type: 'boolean',
  },
];
