import type { SettingDefinition } from './definition.js';

/** Screenshots, save/print panels, sound, and other system-wide behavior. */
export const systemSettings: SettingDefinition[] = [
  {
    section: 'screenshots',
    key: 'save-location',
    description: 'Directory where screenshots are saved.',
    domain: 'com.apple.screencapture',
    defaultsKey: 'location',
    type: 'string',
    restart: 'SystemUIServer',
  },
  {
    section: 'screenshots',
    key: 'format',
    description: 'Screenshot file format.',
    domain: 'com.apple.screencapture',
    defaultsKey: 'type',
    type: 'string',
    choices: [
      { value: 'png', label: 'PNG' },
      { value: 'jpg', label: 'JPEG' },
      { value: 'pdf', label: 'PDF' },
      { value: 'tiff', label: 'TIFF' },
      { value: 'heic', label: 'HEIC' },
    ],
    restart: 'SystemUIServer',
  },
  {
    section: 'screenshots',
    key: 'show-cursor',
    description: 'Include the pointer in screenshots.',
    domain: 'com.apple.screencapture',
    defaultsKey: 'show-cursor',
    type: 'boolean',
    restart: 'SystemUIServer',
  },
  {
    section: 'screenshots',
    key: 'disable-shadow',
    description: 'Omit the drop shadow when capturing a window.',
    domain: 'com.apple.screencapture',
    defaultsKey: 'disable-shadow',
    type: 'boolean',
    restart: 'SystemUIServer',
  },
  {
    section: 'screenshots',
    key: 'show-thumbnail',
    description: 'Show the floating thumbnail after taking a screenshot.',
    domain: 'com.apple.screencapture',
    defaultsKey: 'show-thumbnail',
    type: 'boolean',
    restart: 'SystemUIServer',
  },
  {
    section: 'region',
    key: 'force-24-hour-time',
    description: 'Use 24-hour time regardless of the locale default.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleICUForce24HourTime',
    type: 'boolean',
  },
  {
    section: 'region',
    key: 'temperature-unit',
    description: 'Temperature unit.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleTemperatureUnit',
    type: 'string',
    choices: [
      { value: 'Celsius', label: 'Celsius' },
      { value: 'Fahrenheit', label: 'Fahrenheit' },
    ],
  },
  {
    section: 'region',
    key: 'measurement-units',
    description: 'Measurement units.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleMeasurementUnits',
    type: 'string',
    choices: [
      { value: 'Centimeters', label: 'Centimeters' },
      { value: 'Inches', label: 'Inches' },
    ],
  },
  {
    section: 'region',
    key: 'metric-units',
    description: 'Use the metric system.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleMetricUnits',
    type: 'boolean',
  },
  {
    section: 'region',
    key: 'first-day-of-week',
    description:
      'First day of the week per calendar, e.g. {"gregorian": 2} where 1 = Sunday and 2 = Monday. Structured value.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'AppleFirstWeekday',
    type: 'plist',
  },
  {
    section: 'system',
    key: 'default-app-handlers',
    description:
      'Default applications for file types and URL schemes (browser, mail client, and so on), as macOS Launch Services stores them. Structured value; takes effect after logging out and back in.',
    domain: 'com.apple.LaunchServices/com.apple.launchservices.secure',
    defaultsKey: 'LSHandlers',
    type: 'plist',
    risk: 'caution',
    requiresLogout: true,
  },
  {
    section: 'system',
    key: 'crash-reporter-dialog',
    description: 'Crash reporter dialog style (a hidden preference).',
    domain: 'com.apple.CrashReporter',
    defaultsKey: 'DialogType',
    type: 'string',
    choices: [
      { value: 'basic', label: 'Basic' },
      { value: 'developer', label: 'Developer' },
      { value: 'none', label: 'None' },
    ],
  },
  {
    section: 'system',
    key: 'save-to-icloud-by-default',
    label: 'Save to iCloud by Default',
    description: 'Default new documents to iCloud Drive instead of the local disk.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSDocumentSaveNewDocumentsToCloud',
    type: 'boolean',
  },
  {
    section: 'system',
    key: 'expand-save-panel',
    description: 'Expand the save panel to its detailed view by default.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSNavPanelExpandedStateForSaveMode',
    type: 'boolean',
  },
  {
    section: 'system',
    key: 'expand-print-panel',
    description: 'Expand the print panel to its detailed view by default.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'PMPrintingExpandedStateForPrint2',
    type: 'boolean',
  },
  {
    section: 'system',
    key: 'restore-windows-on-relaunch',
    description: "Reopen an app's windows when you relaunch it after quitting.",
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSQuitAlwaysKeepsWindows',
    type: 'boolean',
  },
  {
    section: 'system',
    key: 'sidebar-icon-size',
    description: 'Sidebar icon size across apps.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'NSTableViewDefaultSizeMode',
    type: 'integer',
    choices: [
      { value: 1, label: 'Small' },
      { value: 2, label: 'Medium' },
      { value: 3, label: 'Large' },
    ],
  },
  {
    section: 'system',
    key: 'alert-volume',
    description: 'Alert (beep) volume.',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.sound.beep.volume',
    type: 'float',
    range: { min: 0, max: 1 },
  },
  {
    section: 'system',
    key: 'ui-sound-effects',
    description: 'Play user interface sound effects (emptying the Trash, screenshots, and so on).',
    domain: 'NSGlobalDomain',
    defaultsKey: 'com.apple.sound.uiaudio.enabled',
    type: 'boolean',
  },
];
